sudo: required
language: java
jdk: oraclejdk8
services:
  - docker
script:
  - gradle clean
  - gradle wrapper
  - ./gradlew build buildDocker --info


after_success:
- bash <(curl -s https://codecov.io/bash)
- docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD";
  docker push reactivesw/cart;
  docker push reactivesw/category;
  docker push reactivesw/config;
  docker push reactivesw/customer-authentication;
  docker push reactivesw/customer-info;
  docker push reactivesw/inventory;
  docker push reactivesw/order;
  docker push reactivesw/payment;
  docker push reactivesw/product;
  docker push reactivesw/producttype;
