apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-data-volume
  namespace: dev
  labels:
    name: pg-data-volume
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    fsType: ext4
    pdName: pg-data-disk